Repository aicoe-aiops/sync-pipelines, pull requests merged in 2020-08, with the labels that each got.

#8 Automatic update of dependency jinja2 from 2.11.2 to 3.0.0a1
  Pipfile.lock
Labels: approved, bot

#9 Update readme to fit Solgate
  README.md
Labels: documentation

#14 Remove dead code from key formatter
  solgate/utils/io.py
Labels: bug

#15 Set pipenv to not install prereleases
  Pipfile
  Pipfile.lock
Labels: bug

#19 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot

#20 Transfer multiple file to multiple locations at once
  Pipfile
  Pipfile.lock
  solgate/__init__.py
  solgate/cli.py
  solgate/transfer.py
  solgate/utils/__init__.py
  solgate/utils/io.py
  tests/conftest.py
  tests/fixtures/different_clients.ini
  tests/fixtures/same_client.ini
  tests/fixtures/same_flags.ini
  tests/fixtures/without_source_formatter.ini
  tests/transfer_test.py
  tests/utils/io_test.py
Labels: enhancement
