Repository aicoe-aiops/sync-pipelines, pull requests merged in 2020-09, with the labels that each got.

#24 Automatic update of dependency s3fs from 0.4.2 to 0.5.1
  Pipfile.lock
Labels: approved, bot

#25 Automatic update of dependency pytest-mock from 3.2.0 to 3.3.1
  Pipfile.lock
Labels: approved, bot

#26 Automatic update of dependency moto from 1.3.14 to 1.3.16
  Pipfile.lock
Labels: approved, bot

#27 Downgrade s3fs to 0.4
  Pipfile
  Pipfile.lock
Labels: bug, thoth/potential-observation

#29 Map solgate images to pull from quay.io
  manifests/base/image-transformer-configuration.yaml
  manifests/base/kustomization.yaml
Labels: enhancement

#34 Release of version 3.0.0
  CHANGELOG.md
  solgate/version.py
Labels: approved, bot

#38 Release of version 3.0.1
  CHANGELOG.md
  solgate/version.py
Labels: approved, bot
