Repository aicoe-aiops/sync-pipelines, pull requests merged in 2021-11, with the labels that each got.

#119 Fix file counting and up the read timeout on S3
  solgate/cli.py
  solgate/transfer.py
  solgate/utils/io.py
  solgate/utils/s3.py
Labels: approved, size/S

#124 Add accorvin to OWNERS file
  OWNERS
Labels: approved, size/XS, lgtm, ok-to-test

#125 Adjust floorist timedelta to 24 hours for failsafe
  manifests/overlays/prod/floorist/floorist.enc.yaml
Labels: approved, size/XS, lgtm

#126 Reschedule floorist to run only once a day for now
  manifests/overlays/prod/floorist/cronwf.yaml
  manifests/overlays/prod/floorist/floorist.enc.yaml
Labels: approved, size/XS, lgtm

#127 Fix sops metadata for floorist file
  manifests/overlays/prod/floorist/floorist.enc.yaml
Labels: approved, size/S, lgtm
