Repository aicoe-aiops/sync-pipelines, pull requests merged in 2022-01, with the labels that each got.

#128 chore: Report Tower analytics to datahub not to tumido
  manifests/overlays/prod/tower-analytics-prod/secret.enc.yaml
  manifests/overlays/prod/tower-analytics-stage/secret.enc.yaml
Labels: size/S

#129 fix: Retry on failures
  manifests/base/wftmpl.yaml
Labels: approved, size/XS, lgtm

#131 fix(test): Update test suite for #119
  tests/cli_test.py
  tests/transfer_test.py
  tests/utils/io_test.py
Labels: approved, size/M

#132 feat: Update USIR creds
  manifests/overlays/prod/usir/secret.enc.yaml
Labels: approved, size/S

#130 Update copy function to use boto3
  solgate/transfer.py
  solgate/utils/s3.py
  tests/conftest.py
  tests/transfer_test.py
  tests/utils/s3_test.py
Labels: approved, size/M, lgtm

#135 Add accorvin as a maintainer
  .thoth.yaml
Labels: size/XS
